### ISSUE TITLE
App is broken on OSX

### ISSUE THREAD

**Issue by Mythli** [ZUGFeRD/quba-viewer#42] opened 2024-03-01 08:06 UTC
The app shows a dialog with 

```
“Quba.app” is damaged and can’t be opened. You should move it to the Bin.
```

```
Software:

    System Software Overview:

      System Version: macOS 13.3.1 (22E261)
      Kernel Version: Darwin 22.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Tobias-MBP-14
      User Name: Tobias Anhalt (tobiasanhalt)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 4 minutes, 37 seconds

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac14,9
      Model Number: MPHH3ZE/A
      Chip: Apple M2 Pro
      Total Number of Cores: 10 (6 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 8422.100.650
      OS Loader Version: 8422.100.650
      Serial Number (system): FWYPNYKVDP
      Hardware UUID: 580133E3-C9DB-52C0-B311-876C804521EE
      Provisioning UDID: 00006020-001C51A01E6B401E
      Activation Lock Status: Disabled
```

**Comment by jstaerk** [comment] 2024-03-09 08:08
apologies that it's broken in the first place and apologies it took us so long to confirm, we'll re-build and re-upload

**Comment by corny** [comment] 2024-03-18 22:05
Please close this issue after you've re-uploaded the working package.

**Comment by jstaerk** [comment] 2024-03-21 10:26
We re-build and re-uploaded but we didnt get it to work on Sonoma yet (interestingly, the identical local file before the upload/download works), can anybody please tell us if it's working on Sonoma and/or other versions?

**Comment by mameier** [comment] 2024-03-23 19:12
Just tried on MacBook Pro M1 with Sonoma and it still reports broken app.
![Bildschirmfoto 2024-03-23 um 20 11 01](https://github.com/ZUGFeRD/quba-viewer/assets/389378/734af096-c105-4c82-87f1-d1ad04e3e997)

**Comment by corny** [comment] 2024-03-25 10:36
Duplicate of #26

**Comment by jstaerk** [comment] 2024-04-29 12:31
can someone pls check if it works with disabled gatekeeper https://iboysoft.com/news/app-is-damaged-and-cannot-be-opened.html ? We're still working our way into https://www.electronjs.org/docs/latest/tutorial/code-signing...

**Comment by jstaerk** [comment] 2024-05-03 15:18
apparently we can now codesign but not notarize https://github.com/electron/notarize/issues/175
https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues

**Comment by jstaerk** [comment] 2024-05-09 07:27
It took my colleague in total *several* working days but finally we're back and better than before, not only is our code now 
 . I hope the colleague can show the *other* colleague (or anybody else- any volunteers?) how to take care of #23 as well. But ote besides, this is a dupe of #26.

**Closed by jstaerk** 2024-05-09 07:27 UTC
